spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: r00t
spring.jpa:
  hibernate:
    ddl-auto: create-drop
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  properties:
    hibernate:
      properties:
        hibernate:
          temp:
            use_jdbc_metadata_defaults: false
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQL9Dialect

